### ISSUE TITLE
 No virtual method areNotificationsEnabled()Z

### ISSUE THREAD

**Issue by erdemildiz** [localytics/react-native-template-app#4]
I am getting blow error 
`11-07 08:20:15.127 4905-4921/com.localyticspush E/AndroidRuntime: FATAL EXCEPTION: AnalyticsHandler
                                                                  Process: com.localyticspush, PID: 4905
                                                                  java.lang.NoSuchMethodError: No virtual method areNotificationsEnabled()Z in class Landroid/support/v4/app/NotificationManagerCompat; or its super classes (declaration of 'android.support.v4.app.NotificationManagerCompat' appears in /data/app/com.localyticspush-1/split_lib_dependencies_apk.apk)
                                                                      at com.localytics.android.Utils.areNotificationsEnabled(Utils.java:400)
                                                                      at com.localytics.android.AnalyticsHeader.setupHeader(AnalyticsHeader.java:112)
                                                                      at com.localytics.android.AnalyticsHeader.<init>(AnalyticsHeader.java:32)
                                                                      at com.localytics.android.AnalyticsHandler._tagOpenEvent(AnalyticsHandler.java:1068)
                                                                      at com.localytics.android.AnalyticsHandler._open(AnalyticsHandler.java:1411)
                                                                      at com.localytics.android.AnalyticsHandler$3.run(AnalyticsHandler.java:516)
                                                                      at com.localytics.android.BaseProvider.runBatchTransaction(BaseProvider.java:403)
                                                                      at com.localytics.android.BaseHandler._runBatchTransactionOnProvider(BaseHandler.java:154)
                                                                      at com.localytics.android.AnalyticsHandler.handleMessageExtended(AnalyticsHandler.java:507)
                                                                      at com.localytics.android.BaseHandler.handleMessage(BaseHandler.java:135)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:154)
                                                                      at android.os.HandlerThread.run(HandlerThread.java:61)`

**Comment by hariganesan** [comment]
It looks like you need a more recent version of the Android support library v4 -- at least 24.1.0 -- in order to use `NotificationManagerCompat.areNotificationsEnabled()`

**Comment by erdemildiz** [comment]
Hello @hariganesan  thanks for your answer. unfortunately I am getting different issue. could you help me?

`FATAL EXCEPTION: ManifestHandler
                                                                  Process: com.localyticspush, PID: 5659
                                                                  java.lang.NoClassDefFoundError: com.localytics.android.BackgroundService
                                                                      at com.localytics.android.ManifestHandler.cancelBackgroundTask(ManifestHandler.java:180)
                                                                      at com.localytics.android.ManifestHandler._onUploadCompleted(ManifestHandler.java:162)
                                                                      at com.localytics.android.BaseHandler._uploadCallback(BaseHandler.java:326)
                                                                      at com.localytics.android.BaseHandler$3.run(BaseHandler.java:129)
                                                                      at com.localytics.android.BaseProvider.runBatchTransaction(BaseProvider.java:403)
                                                                      at com.localytics.android.BaseHandler._runBatchTransactionOnProvider(BaseHandler.java:154)
                                                                      at com.localytics.android.BaseHandler.handleMessage(BaseHandler.java:125)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:148)
                                                                      at android.os.HandlerThread.run(HandlerThread.java:61)`

**Comment by erdemildiz** [comment]
@hariganesan My manifest file look like;

`<manifest 
    xmlns:android="http://schemas.android.com/apk/res/android" package="com.localyticspush" android:versionCode="1" android:versionName="1.0">
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
    <uses-sdk android:minSdkVersion="16" android:targetSdkVersion="22" />
    <application android:name=".MainApplication" android:allowBackup="true" android:label="@string/app_name" android:icon="@mipmap/ic_launcher" android:theme="@style/AppTheme">
        <activity android:name=".MainActivity" android:label="@string/app_name" android:configChanges="keyboard|keyboardHidden|orientation|screenSize" android:windowSoftInputMode="adjustResize">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
                <data android:scheme="ampxxxxxxx" />
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
            </intent-filter>
        </activity>
        <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
        <receiver android:name="com.localytics.android.ReferralReceiver" android:exported="true">
            <intent-filter>
                <action android:name="com.android.vending.INSTALL_REFERRER" />
            </intent-filter>
        </receiver>
        <meta-data android:name="LOCALYTICS_APP_KEY" android:value="xxxxxx" />
    </application>
</manifest>`

**Comment by hariganesan** [comment]
It looks like you are trying to include Localytics separately in your app's gradle -- our react native dependency will pull in Localytics for you. If you have other issues, please file them under a separate issue within Github.

**Comment by erdemildiz** [comment]
thanks @hariganesan , now It work now
